# Generated by Django 4.2.5 on 2024-02-14 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickets',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message_ticket',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message_ticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_message.tickets'),
        ),
        migrations.AddField(
            model_name='message_dialog',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='app_message.dialogs'),
        ),
        migrations.AddField(
            model_name='message_dialog',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialogs',
            name='first_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialogs',
            name='second_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
