# Generated by Django 4.2.5 on 2024-02-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_message', '0005_alter_message_dialog_date_alter_tickets_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_dialog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_images/'),
        ),
    ]
