# Generated by Django 4.2.5 on 2024-02-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_message', '0004_remove_tickets_title_tickets_dedline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_dialog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
